<?php
/**
 * @file
 * asc_news.views_default.inc
 */

/**
 * Implements hook_views_default_views().
 */
function asc_news_views_default_views() {
  $export = array();

  $view = new view;
  $view->name = 'news';
  $view->description = 'Views for News Content Type';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'News';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'News';
  $handler->display->display_options['css_class'] = 'features-list features';
  $handler->display->display_options['use_ajax'] = TRUE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['query']['options']['query_comment'] = FALSE;
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '7';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['expose']['items_per_page_options_all'] = 0;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['hide_empty'] = 0;
  $handler->display->display_options['row_options']['default_field_elements'] = 1;
  /* Footer: Global: Text area */
  $handler->display->display_options['footer']['area']['id'] = 'area';
  $handler->display->display_options['footer']['area']['table'] = 'views';
  $handler->display->display_options['footer']['area']['field'] = 'area';
  $handler->display->display_options['footer']['area']['label'] = 'Read More Icon';
  $handler->display->display_options['footer']['area']['empty'] = FALSE;
  $handler->display->display_options['footer']['area']['content'] = '<a href="/news" title="News Page">&nbsp;</a>';
  $handler->display->display_options['footer']['area']['format'] = 'full_html';
  $handler->display->display_options['footer']['area']['tokenize'] = 0;
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_news_image']['id'] = 'field_news_image';
  $handler->display->display_options['fields']['field_news_image']['table'] = 'field_data_field_news_image';
  $handler->display->display_options['fields']['field_news_image']['field'] = 'field_news_image';
  $handler->display->display_options['fields']['field_news_image']['label'] = '';
  $handler->display->display_options['fields']['field_news_image']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_news_image']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_news_image']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_news_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_news_image']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_news_image']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_news_image']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_news_image']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_news_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_news_image']['settings'] = array(
    'image_style' => 'thumbnail',
    'image_link' => '',
  );
  $handler->display->display_options['fields']['field_news_image']['field_api_classes'] = 0;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = 0;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = 0;
  $handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['title']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['title']['alter']['html'] = 0;
  $handler->display->display_options['fields']['title']['hide_empty'] = 0;
  $handler->display->display_options['fields']['title']['empty_zero'] = 0;
  $handler->display->display_options['fields']['title']['link_to_node'] = 1;
  /* Field: Content: Teaser */
  $handler->display->display_options['fields']['field_ascnews_teaser']['id'] = 'field_ascnews_teaser';
  $handler->display->display_options['fields']['field_ascnews_teaser']['table'] = 'field_data_field_ascnews_teaser';
  $handler->display->display_options['fields']['field_ascnews_teaser']['field'] = 'field_ascnews_teaser';
  $handler->display->display_options['fields']['field_ascnews_teaser']['label'] = '';
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_ascnews_teaser']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_ascnews_teaser']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_ascnews_teaser']['field_api_classes'] = 0;
  /* Field: Content: Updated date */
  $handler->display->display_options['fields']['changed']['id'] = 'changed';
  $handler->display->display_options['fields']['changed']['table'] = 'node';
  $handler->display->display_options['fields']['changed']['field'] = 'changed';
  $handler->display->display_options['fields']['changed']['label'] = '';
  $handler->display->display_options['fields']['changed']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['external'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['changed']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['changed']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['html'] = 0;
  $handler->display->display_options['fields']['changed']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['changed']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['changed']['hide_empty'] = 0;
  $handler->display->display_options['fields']['changed']['empty_zero'] = 0;
  $handler->display->display_options['fields']['changed']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['changed']['date_format'] = 'date';
  /* Sort criterion: Content: Sticky */
  $handler->display->display_options['sorts']['sticky']['id'] = 'sticky';
  $handler->display->display_options['sorts']['sticky']['table'] = 'node';
  $handler->display->display_options['sorts']['sticky']['field'] = 'sticky';
  $handler->display->display_options['sorts']['sticky']['order'] = 'DESC';
  /* Sort criterion: Content: Post date */
  $handler->display->display_options['sorts']['created']['id'] = 'created';
  $handler->display->display_options['sorts']['created']['table'] = 'node';
  $handler->display->display_options['sorts']['created']['field'] = 'created';
  $handler->display->display_options['sorts']['created']['order'] = 'DESC';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'qs_news' => 'qs_news',
  );
  /* Filter criterion: Content: Promoted to front page */
  $handler->display->display_options['filters']['promote']['id'] = 'promote';
  $handler->display->display_options['filters']['promote']['table'] = 'node';
  $handler->display->display_options['filters']['promote']['field'] = 'promote';
  $handler->display->display_options['filters']['promote']['value'] = '1';

  /* Display: Page */
  $handler = $view->new_display('news_page', 'Page', 'page');
  $handler->display->display_options['defaults']['css_class'] = FALSE;
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'node';
  $handler->display->display_options['row_options']['links'] = 0;
  $handler->display->display_options['row_options']['comments'] = 0;
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['footer'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'qs_news' => 'qs_news',
  );
  $handler->display->display_options['path'] = 'news';

  /* Display: Small Feature */
  $handler = $view->new_display('block', 'Small Feature', 'news_block_small');
  $handler->display->display_options['display_description'] = 'Feature with news listed vertically.';
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '4';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_news_image']['id'] = 'field_news_image';
  $handler->display->display_options['fields']['field_news_image']['table'] = 'field_data_field_news_image';
  $handler->display->display_options['fields']['field_news_image']['field'] = 'field_news_image';
  $handler->display->display_options['fields']['field_news_image']['label'] = '';
  $handler->display->display_options['fields']['field_news_image']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_news_image']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_news_image']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_news_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_news_image']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_news_image']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_news_image']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_news_image']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_news_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_news_image']['settings'] = array(
    'image_style' => 'thumbnail',
    'image_link' => '',
  );
  $handler->display->display_options['fields']['field_news_image']['field_api_classes'] = 0;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = 0;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = 0;
  $handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['title']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['title']['alter']['html'] = 0;
  $handler->display->display_options['fields']['title']['hide_empty'] = 0;
  $handler->display->display_options['fields']['title']['empty_zero'] = 0;
  $handler->display->display_options['fields']['title']['link_to_node'] = 1;
  /* Field: Content: Updated date */
  $handler->display->display_options['fields']['changed']['id'] = 'changed';
  $handler->display->display_options['fields']['changed']['table'] = 'node';
  $handler->display->display_options['fields']['changed']['field'] = 'changed';
  $handler->display->display_options['fields']['changed']['label'] = '';
  $handler->display->display_options['fields']['changed']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['external'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['changed']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['changed']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['html'] = 0;
  $handler->display->display_options['fields']['changed']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['changed']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['changed']['hide_empty'] = 0;
  $handler->display->display_options['fields']['changed']['empty_zero'] = 0;
  $handler->display->display_options['fields']['changed']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['changed']['date_format'] = 'date';

  /* Display: Large Feature */
  $handler = $view->new_display('block', 'Large Feature', 'news_block_large');
  $handler->display->display_options['display_description'] = 'Large Feature for Front Page';
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '2';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'grid';
  $handler->display->display_options['style_options']['columns'] = '2';
  $handler->display->display_options['style_options']['fill_single_line'] = 1;
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['hide_empty'] = 0;
  $handler->display->display_options['row_options']['default_field_elements'] = 1;
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['footer'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_news_image']['id'] = 'field_news_image';
  $handler->display->display_options['fields']['field_news_image']['table'] = 'field_data_field_news_image';
  $handler->display->display_options['fields']['field_news_image']['field'] = 'field_news_image';
  $handler->display->display_options['fields']['field_news_image']['label'] = '';
  $handler->display->display_options['fields']['field_news_image']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_news_image']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_news_image']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_news_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_news_image']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_news_image']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_news_image']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_news_image']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_news_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_news_image']['settings'] = array(
    'image_style' => 'large_feature_square',
    'image_link' => '',
  );
  $handler->display->display_options['fields']['field_news_image']['field_api_classes'] = 0;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = 0;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = 0;
  $handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['title']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['title']['alter']['html'] = 0;
  $handler->display->display_options['fields']['title']['hide_empty'] = 0;
  $handler->display->display_options['fields']['title']['empty_zero'] = 0;
  $handler->display->display_options['fields']['title']['link_to_node'] = 1;
  /* Field: Content: Teaser */
  $handler->display->display_options['fields']['field_ascnews_teaser']['id'] = 'field_ascnews_teaser';
  $handler->display->display_options['fields']['field_ascnews_teaser']['table'] = 'field_data_field_ascnews_teaser';
  $handler->display->display_options['fields']['field_ascnews_teaser']['field'] = 'field_ascnews_teaser';
  $handler->display->display_options['fields']['field_ascnews_teaser']['label'] = '';
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_ascnews_teaser']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_ascnews_teaser']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_ascnews_teaser']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_ascnews_teaser']['field_api_classes'] = 0;
  /* Field: Content: Updated date */
  $handler->display->display_options['fields']['changed']['id'] = 'changed';
  $handler->display->display_options['fields']['changed']['table'] = 'node';
  $handler->display->display_options['fields']['changed']['field'] = 'changed';
  $handler->display->display_options['fields']['changed']['label'] = '';
  $handler->display->display_options['fields']['changed']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['external'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['changed']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['changed']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['html'] = 0;
  $handler->display->display_options['fields']['changed']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['changed']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['changed']['hide_empty'] = 0;
  $handler->display->display_options['fields']['changed']['empty_zero'] = 0;
  $handler->display->display_options['fields']['changed']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['changed']['date_format'] = 'date';
  $handler->display->display_options['block_description'] = 'News Feature Small';

  /* Display: Large Right Column */
  $handler = $view->new_display('attachment', 'Large Right Column', 'news_block_large_attachment');
  $handler->display->display_options['display_description'] = 'News List without pictures.';
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '4';
  $handler->display->display_options['pager']['options']['offset'] = '2';
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = 0;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = 0;
  $handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['title']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['title']['alter']['html'] = 0;
  $handler->display->display_options['fields']['title']['hide_empty'] = 0;
  $handler->display->display_options['fields']['title']['empty_zero'] = 0;
  $handler->display->display_options['fields']['title']['link_to_node'] = 1;
  /* Field: Content: Updated date */
  $handler->display->display_options['fields']['changed']['id'] = 'changed';
  $handler->display->display_options['fields']['changed']['table'] = 'node';
  $handler->display->display_options['fields']['changed']['field'] = 'changed';
  $handler->display->display_options['fields']['changed']['label'] = '';
  $handler->display->display_options['fields']['changed']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['external'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['changed']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['changed']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['html'] = 0;
  $handler->display->display_options['fields']['changed']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['changed']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['changed']['hide_empty'] = 0;
  $handler->display->display_options['fields']['changed']['empty_zero'] = 0;
  $handler->display->display_options['fields']['changed']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['changed']['date_format'] = 'date';
  $handler->display->display_options['displays'] = array(
    'news_block_large' => 'news_block_large',
    'default' => 0,
    'page' => 0,
    'news_block_small' => 0,
    'news_block_list' => 0,
  );
  $handler->display->display_options['attachment_position'] = 'after';

  /* Display: News List */
  $handler = $view->new_display('block', 'News List', 'news_block_list');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = 'Recent News';
  $handler->display->display_options['display_description'] = 'News list block for sidebar on news story page.';
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '7';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_news_image']['id'] = 'field_news_image';
  $handler->display->display_options['fields']['field_news_image']['table'] = 'field_data_field_news_image';
  $handler->display->display_options['fields']['field_news_image']['field'] = 'field_news_image';
  $handler->display->display_options['fields']['field_news_image']['label'] = '';
  $handler->display->display_options['fields']['field_news_image']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_news_image']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_news_image']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_news_image']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_news_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_news_image']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_news_image']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_news_image']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_news_image']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_news_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_news_image']['settings'] = array(
    'image_style' => 'thumbnail',
    'image_link' => '',
  );
  $handler->display->display_options['fields']['field_news_image']['field_api_classes'] = 0;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = 0;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = 0;
  $handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['title']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['title']['alter']['html'] = 0;
  $handler->display->display_options['fields']['title']['hide_empty'] = 0;
  $handler->display->display_options['fields']['title']['empty_zero'] = 0;
  $handler->display->display_options['fields']['title']['link_to_node'] = 1;
  /* Field: Content: Updated date */
  $handler->display->display_options['fields']['changed']['id'] = 'changed';
  $handler->display->display_options['fields']['changed']['table'] = 'node';
  $handler->display->display_options['fields']['changed']['field'] = 'changed';
  $handler->display->display_options['fields']['changed']['label'] = '';
  $handler->display->display_options['fields']['changed']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['external'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['changed']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['changed']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['changed']['alter']['html'] = 0;
  $handler->display->display_options['fields']['changed']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['changed']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['changed']['hide_empty'] = 0;
  $handler->display->display_options['fields']['changed']['empty_zero'] = 0;
  $handler->display->display_options['fields']['changed']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['changed']['date_format'] = 'date';
  $export['news'] = $view;

  return $export;
}
